---
title: "Solitude"
author: "Srikanth KS"
output: md_document
---

# Using solitude for anomaly detection

- Srikanth Komala Sheshachala

----

## Introduction

The R package implements **Isolation forest**, an anomaly detection method introduced by the paper Isolation based Anomaly Detection ([Liu, Ting and Zhou](https://dl.acm.org/citation.cfm?id=2133363)). Isolation forest is grown using [ranger](https://cran.r-project.org/package=ranger) package.

‘Isolation forest’ is a multivariate outlier detection technique for IID data containing a mix of numeric and categorical variables.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Usage

```{r}
library("solitude")

data("humus", package = "mvoutlier")
columns_required = setdiff(colnames(humus)
                           , c("Cond", "ID", "XCOO", "YCOO", "LOI")
                           )
humus2 = humus[ , columns_required]
str(humus2)
set.seed(1)
index = sample(ceiling(nrow(humus2) * 0.5))
```


```{r}
# initiate an isolation forest
iso = isolationForest$new(sample_size = length(index))

# fit for attrition data
iso$fit(humus2[index, ])

# Obtain anomaly scores
scores_train = iso$predict(humus2[index, ])
scores_train[order(anomaly_score, decreasing = TRUE)]

# predict scores for unseen data (50% sample)
scores_unseen = iso$predict(humus2[-index, ])
scores_unseen[order(anomaly_score, decreasing = TRUE)]
```

## Anomaly detection

The paper suggests the following: If the score is closer to 1 for a some observations, they are likely outliers. If the score for all observations hover around 0.5, there might not be outliers at all.

By observing the quantiles, we might arrive at the a threshold on the anomaly scores and investigate the outlier suspects.

```{r}
# quantiles of anomaly scores
quantile(scores_unseen$anomaly_score
         , probs = seq(0.5, 1, length.out = 11)
         )
```

The understanding of *why is an observation an anomaly* might require a combination of domain understanding and techniques like lime (Local Interpretable Model-agnostic Explanations), Rule based systems etc

## Installation

```{r, eval = FALSE}
install.packages("solitude")                  # CRAN version
devtools::install_github("talegari/solitude") # dev version
```

----
